#! /bin/sh

opwd=$PWD
tdir=`mktemp -d`
cd $tdir || exit 1
if test -d "$MY_KDEBASE4_OPENSUSE_CHECKOUT"; then
    cp -aR "$MY_KDEBASE4_OPENSUSE_CHECKOUT" kdebase4-openSUSE
    pushd kdebase4-openSUSE
    git checkout -f master
    git pull
    git clean -x -d -f
    popd
else
    git clone git://gitorious.org/opensuse/kdebase4-opensuse.git
    mv kdebase4-opensuse kdebase4-openSUSE
fi
rm -rf kdebase4-openSUSE/.git
svn export svn://anonsvn.kde.org/home/kde/trunk/playground/base/kio_sysinfo kdebase4-openSUSE/sysinfo/kio_sysinfo
if test -d "$MY_LCN_CHECKOUT"; then
  echo "Updating $MY_LCN_CHECKOUT"
  svn up $MY_LCN_CHECKOUT
else
  echo "No \$MY_LCN_CHECKOUT set, will checkout temporarly"
  svn export https://forgesvn1.novell.com/svn/suse-i18n/trunk/lcn
  export MY_LCN_CHECKOUT=$PWD/lcn
fi
pushd kdebase4-openSUSE/po
./fill_po.sh
popd

# remove non-released stuff
for f in update_rpm totranslate/*.sh; do
    rm kdebase4-openSUSE/$f
done

tar -cvj -f $opwd/kdebase4-openSUSE-11.2.tar.bz2 kdebase4-openSUSE
cd /
rm -rf $tdir
