#! /bin/sh

opwd=$PWD
tdir=`mktemp -d`
cd $tdir || exit 1
if test -d "$MY_KDEBASE4_OPENSUSE_CHECKOUT"; then
    cp -aR "$MY_KDEBASE4_OPENSUSE_CHECKOUT" kdebase4-openSUSE
    pushd kdebase4-openSUSE
    git checkout -f openSUSE_11_4_BRANCH
    git pull || exit 1
    git clean -x -d -f
    popd
else
    git clone git://gitorious.org/opensuse/kdebase4-opensuse.git || exit 1
    mv kdebase4-opensuse kdebase4-openSUSE
    pushd kdebase4-openSUSE
    git checkout -f openSUSE_11_4_BRANCH
    popd
fi
rm -rf kdebase4-openSUSE/.git
svn export svn://anonsvn.kde.org/home/kde/trunk/playground/base/kio_sysinfo kdebase4-openSUSE/sysinfo/kio_sysinfo || exit 1
if test -d "$MY_LCN_CHECKOUT"; then
  echo "Updating $MY_LCN_CHECKOUT"
  svn up $MY_LCN_CHECKOUT || exit 1
else
  echo "No \$MY_LCN_CHECKOUT set, will checkout temporarly"
  svn export https://svn.berlios.de/svnroot/repos/opensuse-i18n/trunk/lcn || exit 1
  export MY_LCN_CHECKOUT=$PWD/lcn
fi
pushd kdebase4-openSUSE/po
./fill_po.sh
popd

# remove non-released stuff
for f in update_rpm totranslate/*.sh; do
    rm kdebase4-openSUSE/$f
done

tar -cvj -f $opwd/kdebase4-openSUSE-11.4.tar.bz2 kdebase4-openSUSE
cd /
rm -rf $tdir
